version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=ecommerce
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - ./.db/db:/var/lib/mysql
      - ./.db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql-db:
    driver: local